dist: bionic
language: cpp
comiler:
 - gcc

before_install:
 - sudo apt-get update -qq

install:
 - |
  sudo apt-get install gcc-8 g++-8 gfortran-8 cmake
  sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-8 100
  sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-8 100
  sudo apt-get install -qq openmpi-bin openmpi-common libopenmpi-dev hdf5-tools libhdf5-openmpi-dev cmake

before_script:
 - export PATH=$PATH:$TRAVIS_BUILD_DIR/submodules/cxxtest/bin
 - export CTEST_OUTPUT_ON_FAILURE=1

script:
 - echo "$(uname -r)" && echo "$(uname -a)"
 - cd test/ && mkdir build && cd build
 - cmake -DWITH_UNITTEST=ON -DWITH_HDF5=ON -DWITH_MPI=ON -S .. && make && make test
 - make clean && cmake -E remove ./CMakeCache.txt && cmake -DWITH_UNITTEST=ON -DWITH_HDF5=ON -DWITH_MPI=OFF -S .. && make && make test
 - make clean && cmake -E remove ./CMakeCache.txt && cmake -DWITH_UNITTEST=OFF -DWITH_HDF5=OFF -DWITH_MPI=OFF -S .. && make
