dist: xenial
language: cpp
comiler:
 - gcc
 - clang

before_install:
 - sudo apt-get update -qq

install:
 - sudo apt-get install -qq openmpi-bin openmpi-common libopenmpi-dev libhdf5-openmpi-10 hdf5-tools libhdf5-openmpi-dev cmake

before_script:
 - export PATH=$PATH:$TRAVIS_BUILD_DIR/submodules/cxxtest/bin
 - export CTEST_OUTPUT_ON_FAILURE=1

script:
 - cd test/ && mkdir build && cd build
 - cmake -DWITH_UNITTEST=ON -DWITH_HDF5=ON -DWITH_MPI=ON -S .. && make && make test
 - make clean && cmake -E remove ./CMakeCache.txt && cmake -DWITH_UNITTEST=ON -DWITH_HDF5=ON -DWITH_MPI=OFF -S .. && make && make test
 - make clean && cmake -E remove ./CMakeCache.txt && cmake -DWITH_UNITTEST=OFF -DWITH_HDF5=OFF -DWITH_MPI=OFF -S .. && make